### ISSUE TITLE
pipeline -> workflow

### ISSUE THREAD

**Issue by simonpcouch** [topepo/postprocessing-data#3]
In:

https://github.com/topepo/postprocessing-data/blob/c56bcb1f98281f2d16005b6f6475a4edcdf7ca82/index.qmd#L15-L21

We call this a workflow in tidymodels, no?

**Comment by topepo** [comment]
Most of the world calls it a pipeline; we only don't because we didn't want it to be confused with a magrittr pipeline. I'll add a note that tidymodels calls it a workflow since I want this to be mostly free of implementation details.
